version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: win_academy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: win_academy_db
      POSTGRES_USER: win_academy_user
      POSTGRES_PASSWORD: win_academy_secure_password_2026
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U win_academy_user -d win_academy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: win_academy_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-win-academy-docker-compose-production-key-9923
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      - DATABASE_URL=postgres://win_academy_user:win_academy_secure_password_2026@db:5432/win_academy_db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@winacademy.edu.in
      - DJANGO_SUPERUSER_PASSWORD=WinAcademyAdmin2026!
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
    entrypoint: ["/app/entrypoint.sh"]
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "--threads", "2", "config.wsgi:application"]

volumes:
  postgres_data:
    driver: local
  media_data:
    driver: local
