# Generated by Django 5.1.15 on 2026-08-27 07:59

import academy.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='WIN PROFESSIONAL ACADEMY', help_text='Official institution name', max_length=200)),
                ('trust_name', models.CharField(default='Win Educational Trust', help_text='Trust running the academy', max_length=200)),
                ('trust_reg_no', models.CharField(default='379/2006', help_text='Official Trust Registration Number', max_length=100)),
                ('tagline', models.CharField(default='A Complete Guidelines for Higher Education & Job Service', help_text='Official Academy Tagline', max_length=255)),
                ('primary_phone', models.CharField(default='63817 06581', help_text='Primary contact phone number', max_length=20)),
                ('secondary_phone', models.CharField(default='86681 8494', help_text='Secondary contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, default='info@winacademy.edu.in', help_text='Official email address', max_length=254)),
                ('address', models.TextField(default='Tamil Nadu, India', help_text='Physical office / institution location')),
                ('whatsapp_number', models.CharField(default='6381706581', help_text='WhatsApp contact number without spaces', max_length=20)),
                ('mission', models.TextField(default='To empower every student with expert educational guidance, targeted competitive coaching, and comprehensive pathways towards prestigious universities and fulfilling careers.', help_text='Academy Mission statement')),
                ('vision', models.TextField(default="To stand as Tamil Nadu's premier educational lighthouse, unlocking global academic excellence and career success through dedicated mentorship and uncompromising standards.", help_text='Academy Vision statement')),
                ('higher_education_guidance', models.TextField(default='Comprehensive career mapping and admission assistance for Medical, Paramedical, Engineering, Agriculture, Law, and Arts & Science across Tamil Nadu, all-India institutions, and premier global universities.', help_text='Higher education guidance overview')),
                ('job_services_guidance', models.TextField(default='Dedicated coaching, mock interviews, syllabus mastery, and guidance for competitive teaching examinations (TRB, CSIR-NET, GATE) and governmental career placements.', help_text='Job guidance and services overview')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academy Profile & Branding',
                'verbose_name_plural': 'Academy Profile & Branding',
            },
        ),
        migrations.CreateModel(
            name='AdmissionGuidanceStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('scope', models.CharField(choices=[('TN', 'Tamil Nadu'), ('INDIA', 'All India (National)'), ('ABROAD', 'International & Abroad'), ('ALL', 'Tamil Nadu, India & Abroad')], default='ALL', max_length=20)),
                ('icon_name', models.CharField(default='fas fa-graduation-cap', help_text='CSS icon class or descriptor (e.g. stethoscope, book, atom, tractor, balance-scale, flask)', max_length=60)),
                ('short_description', models.TextField(help_text='Brief highlight of colleges and counselling guidance')),
                ('key_specializations', models.CharField(blank=True, help_text='Comma-separated specializations (e.g., MBBS, BDS, Nursing, B.Tech, LLB)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Admission Guidance Stream',
                'verbose_name_plural': 'Admission Guidance Streams',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by academy administrators')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('target_audience', models.CharField(blank=True, help_text="e.g. 'For College & University Students', 'Competitive Examination Coaching'", max_length=200)),
                ('short_description', models.TextField(help_text='Concise summary shown on course cards')),
                ('full_description', models.TextField(help_text='Detailed course description, curriculum overview, and methodology')),
                ('course_image', models.ImageField(blank=True, help_text='High resolution course banner/card image', null=True, upload_to=academy.validators.course_image_upload_path, validators=[academy.validators.validate_image_file])),
                ('syllabus', models.TextField(blank=True, help_text='Detailed syllabus or key topics (One per line or formatted text)')),
                ('duration', models.CharField(blank=True, default='Comprehensive Annual / Intensive Batch', max_length=100)),
                ('eligibility', models.CharField(blank=True, default='UG/PG Students & Aspirants', max_length=200)),
                ('batch_mode', models.CharField(blank=True, default='Classroom & Live Interactive Sessions', max_length=100)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage featured courses section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether course is visible to public')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief category description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('examination', models.CharField(help_text='e.g. CSIR-NET JRF, GATE Mathematics, PG-TRB, IIT-JAM, University Topper', max_length=150)),
                ('year', models.CharField(default='2025-2026', max_length=20)),
                ('score', models.CharField(blank=True, help_text='Marks / Percentile', max_length=50)),
                ('rank', models.CharField(blank=True, help_text='e.g. AIR 14, State Rank 3', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Student's testimonial or success details")),
                ('student_image', models.ImageField(blank=True, help_text='Student photograph', null=True, upload_to=academy.validators.result_image_upload_path, validators=[academy.validators.validate_image_file])),
                ('is_featured', models.BooleanField(default=True, help_text='Feature on homepage achievements showcase')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Result & Achievement',
                'verbose_name_plural': 'Student Results & Achievements',
                'ordering': ['display_order', '-year', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('educational_qualification', models.CharField(blank=True, help_text='Current qualification (e.g. +2 / B.Sc Maths / B.E / M.Sc)', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Specific requirements or queries')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONTACTED', 'Counselor Contacted'), ('ADMITTED', 'Admission Confirmed'), ('CLOSED', 'Closed / Not Interested')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Counseling status notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_inquiries', to='academy.admissionguidancestream')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_inquiries', to='academy.course')),
            ],
            options={
                'verbose_name': 'Admission & Guidance Application',
                'verbose_name_plural': 'Admission & Guidance Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Notes & Study Guides'), ('NOTE', 'Class Notebooks & Formulas'), ('BOOK', 'Reference Books & Compendiums'), ('SYLLABUS', 'Official Syllabus & Question Banks')], default='PDF', max_length=20)),
                ('file', models.FileField(help_text='Upload PDF, DOCX, or study documents (max 50MB)', upload_to=academy.validators.course_material_upload_path, validators=[academy.validators.validate_document_file])),
                ('is_public', models.BooleanField(default=True, help_text='If True, accessible for public download')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course')),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
